#!/bin/bash
# Dagzo OS live-build konfiguratsiyasi — Kali rolling asosida

lb config noauto \
    --architectures amd64 \
    --distribution kali-rolling \
    --debian-installer false \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends false \
    --hostname dagzo \
    --username dagzo \
    --system-label "Dagzo OS" \
    --iso-volume "Dagzo OS" \
    --iso-publisher "Dagzo Education" \
    --iso-application "Dagzo OS" \
    --bootappend-live "boot=live components live-config username=dagzo hostname=dagzo quiet splash nomodeset" \
    --binary-images iso-hybrid \
    --memtest none \
    --win32-loader false \
    --mirror-bootstrap "http://http.kali.org/kali" \
    --mirror-chroot "http://http.kali.org/kali" \
    --mirror-binary "http://http.kali.org/kali" \
    "${@}"
