#!/bin/bash
# Dagzo OS live-build konfiguratsiyasi

lb config noauto \
    --architectures amd64 \
    --distribution bookworm \
    --debian-installer false \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends false \
    --hostname dagzo \
    --username dagzo \
    --system-label "Dagzo OS" \
    --iso-volume "Dagzo OS" \
    --iso-publisher "Dagzo Education" \
    --iso-application "Dagzo OS" \
    --bootappend-live "boot=live components quiet splash nomodeset" \
    --binary-images iso-hybrid \
    --memtest none \
    --win32-loader false \
    "${@}"
